### ISSUE TITLE
LittleFS Doesn't compile

### ISSUE THREAD

**Issue by tuckjohn** [PaulStoffregen/LittleFS#17]
Hi! I am trying to use this library on a Teensy 4.1 with a W25Q512JV (64MB Serial Flash) chip, but am having trouble getting the library to compile. 
If I try to compile this code:
```
#include <LittleFS.h>
void setup(){}
void loop(){}
```
I get this error:
```
In file included from C:\Users\username\AppData\Local\Temp\arduino_modified_sketch_815385\LitteFS_simple_datalogger.ino:1:0:

C:\Users\username\Documents\Arduino\libraries\LittleFS-main\src/LittleFS.h:25:16: fatal error: FS.h: No such file or directory

compilation terminated.

Error compiling for board Teensy 4.1.
```
Do you have any ideas of what the issue is? Thanks in advance!

Relevant info:
Arduino IDE 1.8.11, Teensyduino 1.53, Windows 10

**Comment by PaulStoffregen** [comment]
Install this
https://forum.pjrc.com/threads/67612-Teensyduino-1-54-Beta-12

**Comment by tuckjohn** [comment]
Great, that worked. Thanks!
