### ISSUE TITLE
Excuse me, where can I find FS.h? 

### ISSUE THREAD

**Issue by M-4A** [PaulStoffregen/LittleFS#36]
Which connects to the library ... 

#pragma once
#include <Arduino.h>
#include <FS.h>
#include <SPI.h>
#include "littlefs/lfs.h"
//#include <algorithm>

Thank you.

**Comment by M-4A** [comment]
Ok.
It's found in cores (github), but that doesn't help anything. Because it still doesn't work ...

**Comment by mjs513** [comment]
Not sure what you mean by still does not work.  You need to provide a lot more details on what sketch are you running, what board, what version of Teensyduino what Teensy board are you using etc?  Otherwise no one can help you on why its not working.

**Comment by PaulStoffregen** [comment]
This is why we have the installers, so you can get a complete set of all libraries which work together.

**Comment by M-4A** [comment]
Thanks for your helpfulness.
Everything is in order, I figured it out.
For some reason, not all of the Teency4 cores files have been installed.
After I downloaded from the github everything works fine now.
Thanks.
