### ISSUE TITLE
Would like a mode option to open() to overwrite an existing file

### ISSUE THREAD

**Issue by technoblogy** [PaulStoffregen/LittleFS#51]
Your wrapper to LittleFS is compatible with the basic Arduino SD library in accepting the following mode arguments to **open()**:

**FILE_READ**: open the file for reading, starting at the beginning of the file.
**FILE_WRITE**: open the file for reading and writing, starting at the end of the file.

See: https://www.arduino.cc/en/Reference/SDopen

However your implementation doesn't seem to provide an easy way to open a file that gets overwritten if it already exists (apart from deleting it first).

Although it's not documented on the Arduino page, most SD implementations provide the following mode option to achieve this:

O_RDWR | O_CREAT | O_TRUNC

Most other implementations of LittleFS (such as on ESP8266, ESP32, and RP2040) use the following options for mode (among others):

**"r"** - Open text file for reading. The stream is positioned at the beginning of the file.

**"w"** - Truncate file to zero length or create text file for writing. The stream is positioned at the beginning of the file.

**"a"** - Open for appending (writing at end of file). The file is created if it does not exist.  The stream is positioned at the end of the file.

See: https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html

so **"a"** behaves like your FILE_WRITE, and **"w"** overwrites an existing file.

Would it be possible to do one of the following:

* Provide FILE_OVERWRITE equivalent to what I'm looking for.
* Support the ESP8266/ESP32 style mode options.
* Support O_RDWR | O_CREAT | O_TRUNC.

**Comment by PaulStoffregen** [comment]
I believe we're supporting FILE_WRITE_BEGIN, same as with the SD library.
